# Regimientos

In [3]:
import pandas as pd

### Paso 2. Crear el DataFrame con los siguientes valores:

In [4]:
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'], 
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'], 
        'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'], 
        'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}

### Paso 3. Asignar a una variable llamada regimiento.

In [5]:
regimiento = pd.DataFrame(data=raw_data)
regimiento

      regiment company      name  preTestScore  postTestScore
0   Nighthawks     1st    Miller             4             25
1   Nighthawks     1st  Jacobson            24             94
2   Nighthawks     2nd       Ali            31             57
3   Nighthawks     2nd    Milner             2             62
4     Dragoons     1st     Cooze             3             70
5     Dragoons     1st     Jacon             4             25
6     Dragoons     2nd    Ryaner            24             94
7     Dragoons     2nd      Sone            31             57
8       Scouts     1st     Sloan             2             62
9       Scouts     1st     Piger             3             70
10      Scouts     2nd     Riani             2             62
11      Scouts     2nd       Ali             3             70

### Paso 4. ¿Cuál es la puntuación media de preTestScore del regimiento Nighthawks?

In [6]:
Nighthawks = regimiento[regimiento['regiment'] == 'Nighthawks']
Nighthawks

     regiment company      name  preTestScore  postTestScore
0  Nighthawks     1st    Miller             4             25
1  Nighthawks     1st  Jacobson            24             94
2  Nighthawks     2nd       Ali            31             57
3  Nighthawks     2nd    Milner             2             62

In [7]:
pretestScore_mean = Nighthawks.groupby('regiment')['preTestScore'].mean()
pretestScore_mean

regiment
Nighthawks    15.25
Name: preTestScore, dtype: float64


### Paso 5. Presentar las estadísticas generales por compañía

In [8]:
regimiento.name.describe()

count      12
unique     11
top       Ali
freq        2
Name: name, dtype: object

### Paso 6. ¿Cuál es la media de las puntuaciones preTestScore de cada empresa?

In [9]:
pretestScore_mean_company = regimiento.groupby(['name'])['preTestScore'].mean()
pretestScore_mean_company

name
Ali         17.0
Cooze        3.0
Jacobson    24.0
Jacon        4.0
Miller       4.0
Milner       2.0
Piger        3.0
Riani        2.0
Ryaner      24.0
Sloan        2.0
Sone        31.0
Name: preTestScore, dtype: float64

### Paso 7. Muestra las puntuaciones medias de preTestScore agrupadas por regimiento y compañía

In [10]:
pretestScore_mean_company_regiment = regimiento.groupby(['regiment', 'company'])['preTestScore'].mean()
pretestScore_mean_company_regiment

regiment    company
Dragoons    1st         3.5
            2nd        27.5
Nighthawks  1st        14.0
            2nd        16.5
Scouts      1st         2.5
            2nd         2.5
Name: preTestScore, dtype: float64

### Paso 8. Presentar la media de las puntuaciones preTestScores agrupadas por regimiento y compañía sin usar indexación jerárquica

In [12]:
mean_preTestScores = regimiento.groupby(['regiment', 'company'])['preTestScore'].mean().reset_index()
mean_preTestScores

     regiment company  preTestScore
0    Dragoons     1st           3.5
1    Dragoons     2nd          27.5
2  Nighthawks     1st          14.0
3  Nighthawks     2nd          16.5
4      Scouts     1st           2.5
5      Scouts     2nd           2.5

### Paso 9. Agrupar todo el marco de datos por regimiento y compañía

In [21]:
data = regimiento.groupby(['regiment', 'company'])
data

### Paso 10. Cuál es el número de observaciones en cada regimiento y compañía

In [20]:
obervaciones = regimiento.groupby(['regiment', 'company']).size()
obervaciones

regiment    company
Dragoons    1st        2
            2nd        2
Nighthawks  1st        2
            2nd        2
Scouts      1st        2
            2nd        2
dtype: int64

### Paso 11. Iterar sobre un grupo e imprimir el nombre y los datos completos del regimiento. Haz una función llamada agrupa(variable)

In [27]:
def agrupa(variable):
    grouped_data = regimiento.groupby(variable)
    
    for nombre, datos in grouped_data:
        print(f"Nombre del {variable}: {nombre}")
        print(datos)
        print("\n")

# Llamada a la función con la columna del dataframe que queramos
agrupa('company')

Nombre del company: 1st
     regiment company      name  preTestScore  postTestScore
0  Nighthawks     1st    Miller             4             25
1  Nighthawks     1st  Jacobson            24             94
4    Dragoons     1st     Cooze             3             70
5    Dragoons     1st     Jacon             4             25
8      Scouts     1st     Sloan             2             62
9      Scouts     1st     Piger             3             70


Nombre del company: 2nd
      regiment company    name  preTestScore  postTestScore
2   Nighthawks     2nd     Ali            31             57
3   Nighthawks     2nd  Milner             2             62
6     Dragoons     2nd  Ryaner            24             94
7     Dragoons     2nd    Sone            31             57
10      Scouts     2nd   Riani             2             62
11      Scouts     2nd     Ali             3             70